first commit

diff --git a/bin/test_automata_env b/bin/test_automata_env
--- a/bin/test_automata_env
+++ b/bin/test_automata_env
@@ -1,10 +1,36 @@
-#!/bin/sh
+#!/bin/bash
 
 #
 # Set environment variables for test implementation
 #
+BIN_DIR=$(dirname $0)
 export TEST_ROOT=$(pwd)
 export RESOURCES=$(dirname $BIN_DIR)/robotframework/resources
+[ -z "$LOCAL_MODE" ] && LOCAL_MODE=false
+
+#
+# Read config file
+#
+CONFIG_FILE=$TEST_ROOT/config
+if [ ! -f $CONFIG_FILE ]; then
+  echo "You need to create config file '${CONFIG_FILE}'"
+  exit 1
+fi
+. $CONFIG_FILE
+if [ "$TARGET_TYPE" != "web" ] && [ "$TARGET_TYPE" != "app" ]; then
+  echo "TARGET_TYPE should be 'web' or 'app'."
+  exit 1
+fi
+if [ "$TARGET_TYPE" = "app" ]; then
+  if [ -z "$APP_NAME" ]; then
+    echo "Missing mandatory environment variable APP_NAME."
+    exit 1
+  fi
+  if [ -z "$APP_VERSION" ]; then
+    echo "Missing mandatory environment variable APP_VERSION."
+    exit 1
+  fi
+fi
 
 #
 # Source .env file if it exists
@@ -25,9 +51,6 @@ if [ -z "$TEST_RESOURCES" ]; then
 fi
 if [ -z "$TEST_CASES" ]; then
   export TEST_CASES=$TEST_ROOT/cases
-fi
-if [ -z "$UA_FILE" ]; then
-  UA_FILE=$TEST_ROOT/ua.csv
 fi
 
 #
@@ -54,33 +77,12 @@ if [ $LOCAL_MODE == false ]; then
 fi
 
 #
-# Check if ua.csv to define testing user agents
+# Check target environment list on browserstack
 #
-if [ $LOCAL_MODE == false ]; then
-  if [ ! -f $UA_FILE ]; then
-    echo "You have to define the testing user agents on $UA_FILE"
-    exit 1
-  fi
-  #
-  # Verify all data
-  #
-  UA_OS=()
-  UA_OS_VERSION=()
-  UA_BROWSER=()
-  UA_BROWSER_VERSION=()
-  while read LINE; do
-    IFS_ORG="$IFS"
-    IFS=$'\n'
-    BROWSER_DATA=(`python $BIN_DIR/bs_validate_browser.py "$LINE"`)
-    if [ $? -ne 0 ]; then
-      echo 'Defined user agent below is not supported by browserstack. See the full list on "https://www.browserstack.com/list-of-browsers-and-platforms/automate"'
-      echo $LINE
-      exit 1
-    fi
-    IFS="$IFS_ORG"
-    export UA_OS=("${UA_OS[@]}" "${BROWSER_DATA[0]}")
-    export UA_OS_VERSION=("${UA_OS_VERSION[@]}" "${BROWSER_DATA[1]}")
-    export UA_BROWSER=("${UA_BROWSER[@]}" "${BROWSER_DATA[2]}")
-    export UA_BROWSER_VERSION=("${UA_BROWSER_VERSION[@]}" "${BROWSER_DATA[3]}")
-  done < $UA_FILE
+if [ "$TARGET_TYPE" = "web" ]; then
+  . $BIN_DIR/test_automata_env_ua
+fi
+if [ "$TARGET_TYPE" = "app" ]; then
+  . $BIN_DIR/test_automata_env_device
+  . $BIN_DIR/test_automata_env_apps
 fi
